[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'

[[plugins]]
repo = 'glidenote/memolist.vim'
