# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.z]
github = "rupa/z"

[plugins.zsh-wakatime]
github = "wbinglee/zsh-wakatime"

[plugins.zsh-notify]
github = "marzocchi/zsh-notify"

[plugins.zsh-dwim]
github = "oknowton/zsh-dwim"

[plugins.mysql-plugin]
github = "voronkovich/mysql.plugin.zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-url-highlighter]
github = "ascii-soup/zsh-url-highlighter"

[plugins.zsh-256color]
github =  "chrissicool/zsh-256color"

[plugins.zsh-colors]
github =  "Tarrasch/zsh-colors"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
